#app.helpers.constants.py
import pytz
BD_TIMEZONE = pytz.timezone('Asia/Dhaka') 

SUCCESS = "Success"
DELETE_SUCCESSFULLY = "Deleted Successfully"
FAILED = "Failed"
COULD_NOT_UPDATE = "Could not update"
COULD_NOT_CREATE = "Could not create"
UNAUTHENTICATED = "Unauthenticated"
UNAUTHORAZED = "You don't have permission to perform this action. If you believe this is a mistake, please contact support."
INTERNAL_SERVER_ERROR = "Something went wrong! Please try again later."
SOMETHING_WENT_WRONG = "Oops! Something went wrong"
USER_NOT_FOUND = "User Not Found"
DATA_NOT_FOUND = "Data not found"
ALREADY_EXISTS = "Already exists"
USER_NOT_FOUND_BY_ID = "User not found with the given ID"
WE_COULD_NOT_FOUND_YOUR_EMAIL = "We couldn't find your email address"
OTP_SEND_TO_EMAIL = "We have sent an OTP in your email address."
OTP_SEND_TO_EMAIL_PHONE = "We have sent OTP in your phone and email address ."
CANNOT_GENERATE_OTP = "Can't regenerate OTP right now!"
OTP_EXPIRED = "OTP Expired!"
INVALID_OTP = "Invalid OTP!"
OTP_VERIFIED = "OTP Verified!"
CURRENT_PASSWORD_NOT_METCHED = "Current password not metched!"
CONFIRM_PASSWORD_NOT_METCHED = "Password do not matched with confirm password!"
NEW_PASSWORD_CANNOT_BE_CURRENT_ONE = "New password cannot be same as the current one!"
PASSWORD_STRENGTH_MISMATCH = "Password must have at least 8 characters, at least one letter and one digit"
SESSION_EXPIRED = "Session expired!"
PASSWORD_UPDATED = "Password successfully updated."
ACTIVE_OTP_EXIST = 'There is an active OTP exists!'
MAX_OTP_LIMIT = 'Maximum OTP limit exceeded!'
INCORRECT_USERNAME_OR_PASS = 'Incorrect username or password'
INVALID_TOKEN = 'Invalid token!'
INVALID_REQUEST = 'Invalid request!'
INVALID_REFRESH_TOKEN = 'Invalid refresh token'
INACTIVE_CLIENT = 'Client is not in the active state'
CSE_VALUE_NOT_FOUND = 'CSE value not found. Please try DSE.'
ALREADY_ADDED_TO_WATCHLIST = "Already added to Watchlist"
INVALID_FORM_DATA = "invalid form data"
SESSION_CONNECTED = "Session Connected"
YOU_ARE_NOT_ALLOWED_TO_LOGIN_ANY_DEVICE = "You are not allowed to login in any device"
YOU_ARE_NOT_ALLOWED_TO_LOGIN_ANY_DESKTOP_DEVICE = "You are not allowed to login in any desktop device"
YOU_ARE_NOT_ALLOWED_TO_LOGIN_ANY_MOBILE_DEVICE = "You are not allowed to login in Mobile device"
LOGIN_FAILED = "Login Failed: Account Disabled"
MAX_ALLOWED_LOGIN_EXTENDED = "Max Allowed Login Exceeded"
MAX_ALLOWED_LOGIN_EXTENDED_FOR_DESKTOP = "Max Allowed Login Exceeded For Desktop"
MAX_ALLOWED_LOGIN_EXTENDED_FOR_MOBILE = "Max Allowed Login Exceeded For Mobile"
ALERT_ALREADY_EXISTS = "Alert already exists"
INVALID_DATE_FORMAT = "Invalid date format"
UPDATED_SUCCESSFULLY = "Updated successfully"
UNKNOWN_ERROR = "Unknown Error!"
DUPLICATE_ENTRY = "Duplicate entry found for a unique field."
IP_ALREADY_EXISTS_FOR_ENTIRY = "IP already added for this entity"
IP_NOT_REGISTERED_FOR_ENTIRY = "IP not registered for this entity"
INCORRECT_PASSWORD = "Incorrect password"
ACTIVE_SESSION_EXISTS = "Active session exists"
INACTIVE_USER = "User is inactive"