worker_processes  auto;

worker_rlimit_nofile 100000;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

# First bash into Nginx Docker Container and run:
# $ apt-get update
# $ apt-get install nginx-extras
# load_module modules/ngx_http_headers_more_filter_module.so;

events {
    worker_connections  4000;

    # optimized to serve many clients with each thread, essential for linux 
    # -- for dev environment
    use epoll;

    # accept as many connections as possible, may flood worker connections if set too low
    # -- for dev environment
    multi_accept on;
}


http {
    
    server_tokens off;
    # more_clear_headers Server;
    # more_set_headers 'Server: Serverless';

    
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    

    # log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                   '$status $body_bytes_sent "$http_referer" '
    #                   '"$http_user_agent" "$http_x_forwarded_for"';

    # access_log  /var/log/nginx/access.log  main;
    
    # to boost I/O on HDD we can disable access logs
    access_log off;

    # copies data between one FD and other from within the kernel
    # faster than read() + write()
    sendfile on;
    
    # send headers in one piece, it is better than sending them one by one
    tcp_nopush on;

    # allow the server to close connection on non responding client, this will free up memory
    reset_timedout_connection on;

    keepalive_timeout  65;

    
    # Enable Compression
    gzip on; 
    gzip_vary on; 
    gzip_min_length 1024; 
    gzip_proxied expired no-cache no-store private auth; 
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml; 
    gzip_disable "MSIE [1-6]\.";

    include /etc/nginx/conf.d/*.conf;
}