server {
    listen 80;
    server_name localhost;
    error_page 400 502 @error;

    location @error {
        default_type text/html;
        return 200 '<body style="background: #18181a; color: #de8f00;"><center><h1>We Are Under Maintenance</h1></center>
        <center><h3 style="color: #bababa;">Please Visit Us Later</h3></body>';
    }

    access_log /var/log/nginx/data-access.log combined;
    
    client_max_body_size 0;

    location / {
        proxy_pass http://ota_api:7700;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect http://ota_api $scheme://$http_host/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 20d;
        proxy_buffering off;
    }
}