from sqlalchemy import Column, String, BigInteger, TIMESTAMP, JSON, ForeignKey
from sqlalchemy.orm import relationship
from databases.database import OtaDbBase
from datetime import datetime

class SupplierConfiguration(OtaDbBase):
    """
    Supplier operational configuration, API credentials, endpoints, and booking rules.
    """
    __tablename__ = "supplier_configurations"

    id                                  = Column(BigInteger, primary_key=True, autoincrement=True)
    supplier_id                         = Column(BigInteger, ForeignKey("suppliers.id", ondelete="CASCADE"), nullable=False, index=True)
    api_endpoints                       = Column(JSON, nullable=True)
    api_credentials                     = Column(JSON, nullable=True)
    api_settings                        = Column(JSON, nullable=True)
    hold_option                         = Column(String(50), nullable=True)
    hold_time_limit                     = Column(String(100), nullable=True)
    hold_booking_time_limit_title       = Column(String(150), nullable=True)
    hold_booking_show_time_limit        = Column(String(50), nullable=True)
    time_limit_delay                    = Column(String(50), nullable=True)
    cancel_hold_booking_option          = Column(String(50), nullable=True)
    process_pnr_ticketing_auto_queue_on = Column(String(100), nullable=True)
    return_flight_result_type           = Column(String(100), nullable=True)
    payment_settlement                  = Column(String(100), nullable=True)
    iata_payment_cycle                  = Column(String(100), nullable=True)
    supplier_color                      = Column(String(50), nullable=True)
    default_airlines                    = Column(String(50), nullable=True)
    city_name                           = Column(String(100), nullable=True)
    state_code                          = Column(String(50), nullable=True)
    flight_passport_id_required         = Column(String(100), nullable=True)
    passport_id_scan_option             = Column(String(50), nullable=True)
    passport_id_expired_check           = Column(String(50), nullable=True)
    passport_id_expired_limit_for_check = Column(String(50), nullable=True)
    domestic_flight_passport_id_required= Column(String(100), nullable=True)
    set_domestic_country                = Column(String(100), nullable=True)
    set_domestic_airlines_code          = Column(String(100), nullable=True)
    meal_selection                      = Column(String(50), nullable=True)
    baggage_selection                   = Column(String(50), nullable=True)
    seat_selection                      = Column(String(50), nullable=True)
    frequent_flyer_option               = Column(String(50), nullable=True)
    passenger_search_option             = Column(String(50), nullable=True)
    wheelchair_option                   = Column(String(50), nullable=True)
    post_booking_meal_selection         = Column(String(50), nullable=True)
    post_booking_baggage_selection      = Column(String(50), nullable=True)
    post_booking_seat_selection         = Column(String(50), nullable=True)
    post_passport_id_scan_option        = Column(String(50), nullable=True)
    extra_meal_add                      = Column(String(50), nullable=True)
    passenger_guest_dob                 = Column(String(50), nullable=True)
    passport_scan_mandatory             = Column(String(50), nullable=True)
    passenger_contact_no_email_fields   = Column(String(50), nullable=True)
    save_passenger_option               = Column(String(50), nullable=True)
    codeshare_flight                    = Column(String(100), nullable=True)
    partial_payment_option              = Column(String(50), nullable=True)
    available_search_option             = Column(JSON, nullable=True)
    notification_email                  = Column(String(150), nullable=True)
    supplier_contacts_option            = Column(String(100), nullable=True)
    supplier_contacts_phone             = Column(String(50), nullable=True)
    supplier_contacts_email             = Column(String(150), nullable=True)
    status_search_book                  = Column(String(50), nullable=True)
    post_booking_status                 = Column(String(50), nullable=True)
    cron_jobs_status                    = Column(String(50), nullable=True)
    module_status                       = Column(String(50), nullable=True)
    partner_can_modify_credentials      = Column(String(50), nullable=True)
    can_book                            = Column(String(50), nullable=True)
    void_refund_ticket_option           = Column(String(50), nullable=True)
    re_issue_ticket_option              = Column(String(50), nullable=True)
    sync_booking_details_option         = Column(String(50), nullable=True)
    update_booking_info_option          = Column(String(50), nullable=True)
    terms_condition_check_tick          = Column(String(50), nullable=True)
    cancellation_policy_check_tick      = Column(String(50), nullable=True)
    enable_cache_service                = Column(String(50), nullable=True)
    refund_quote_option                 = Column(String(50), nullable=True)
    log_settings                        = Column(JSON, nullable=True)
    sync_items                          = Column(JSON, nullable=True)
    notification_schedule               = Column(JSON, nullable=True)
    created_at                          = Column(TIMESTAMP, nullable=True, default=datetime.utcnow)
    updated_at                          = Column(TIMESTAMP, nullable=True, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    supplier                            = relationship("Supplier", back_populates="configuration")
